{
    'name': 'School Management System',
    'author': 'Cambodian Devs Team',
    'license': 'AGPL-3',
    'version': '1.0.1',
    'depends': [
        'base',
        'mail',
        'account',
        ],
    'data': [
        'data/sequence.xml',
        'data/email.xml',
        'security/security.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'views/teacher_view.xml',
        'views/manage_teacher.xml',
        'views/group_view.xml',
        'views/student_view.xml',
        'views/subject_view.xml',
        'views/room_view.xml',
        'views/timetable.xml',
        'views/academic_year.xml',
        'views/semester.xml',
        'views/program_year.xml',
        'views/subject_offering.xml',
        'views/major_view.xml',
        'views/payment.xml',
        'views/res_partner.xml',
        'views/report/report_student_payment_action.xml',
        'views/report/report_student_payment_template.xml',
        'views/purchase_order.xml',
        'views/student_analysis_view.xml',
        'views/study_sesion.xml',
        'views/account_move.xml',
        'views/study_schedule.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'school_MGM/static/src/school_timetable.css',
            'school_MGM/static/src/school_student_kanban.css',
            'school_MGM/static/src/payment_list.css',
        ],
    },
    'installable': True,
    'application': True,
}