from . import teacher
from . import student
from . import group
from . import subject
from . import manage_teacher
from . import room
from . import timetable
from . import grouplabel
from . import academic_year
from . import semester
from . import program_year
from . import subject_offering
from . import major
from . import inactive_student
from . import payment
from . import respartner
from . import purchase
from . import student_analysis
from . import study_schedule
from . import study_sesion
from . import invoice