from . import Car
from . import brand
from . import customer
from . import salesperson
from . import sale_order
from . import cus_car_test
from . import cartestplate
from . import demo_car
from . import wizard